import type { CategoryId } from "./categories";

export type Product = {
  slug: string;
  name: string;
  subtitle: string;
  category: Exclude<CategoryId, "all">;
  categoryLabel: string;
  lotId: string;
  purityLabel: string;
  image: string;
  shortDesc: string;
  fromPrice: number;
  /** Scientific data — surfaced as a small dossier row */
  formula?: string;
  molecularWeight?: string;
  sequence?: string;
  residues?: number;
  cas?: string;
  appearance?: string;
  storage?: string;
  signedOn?: string;
};

/** Order mirrors the live shop page. */
export const PRODUCTS: Product[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    subtitle: "Body Protection Compound 15",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-BPC-2601",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/bpc-157-5mg.jpg",
    shortDesc:
      "A pentadecapeptide fragment derived from a protective protein found in gastric juice. Widely studied in preclinical models of tissue repair, gut mucosal integrity, and angiogenic signaling.",
    fromPrice: 45,
    formula: "C₆₂H₉₈N₁₆O₂₂",
    molecularWeight: "1419.53 g/mol",
    sequence: "GEPPPGKPADDAGLV",
    residues: 15,
    cas: "137525-51-0",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C, protected from light and moisture",
    signedOn: "2026-04-18",
  },
  {
    slug: "repair-stack",
    name: "BB10",
    subtitle: "BPC-157 + TB-500",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-RST-2601",
    purityLabel: "Each component ≥99% HPLC",
    image: "/images/mockups/bb10-10mg.jpg",
    shortDesc:
      "A paired research stack combining BPC-157 and TB-500 in one vial format for investigators studying overlapping tissue-repair, angiogenic, and cell-migration pathways.",
    fromPrice: 89,
    formula: "Co-lyophilized blend",
    molecularWeight: "5 mg + 5 mg per vial",
    sequence: "GEPPPGKPADDAGLV · LKKTETQ",
    residues: 22,
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-12",
  },
  {
    slug: "tb-500",
    name: "TB-500",
    subtitle: "Thymosin β4 fragment",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-TB5-2603",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/tb-500-5mg.jpg",
    shortDesc:
      "A synthetic peptide corresponding to an active region of Thymosin β4, an actin-binding protein involved in cell migration and wound repair in preclinical models.",
    fromPrice: 45,
    formula: "C₃₅H₅₉N₉O₁₁",
    molecularWeight: "789.91 g/mol",
    sequence: "Ac-LKKTETQ-OH",
    residues: 7,
    cas: "77591-33-4",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-05",
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    subtitle: "Copper Tripeptide-1",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-GHK-2601",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/ghk-cu-50mg.jpg",
    shortDesc:
      "A naturally occurring copper-binding tripeptide studied extensively in models of fibroblast activity, collagen synthesis, and skin matrix remodeling.",
    fromPrice: 45,
    formula: "C₁₄H₂₄CuN₆O₄",
    molecularWeight: "419.92 g/mol",
    sequence: "Gly-His-Lys · Cu²⁺",
    residues: 3,
    cas: "89030-95-5",
    appearance: "Blue lyophilized powder",
    storage: "Ambient handling, lyophilized; cool dry storage recommended",
    signedOn: "2026-03-22",
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295 (no DAC)",
    subtitle: "Modified GRF(1-29)",
    category: "gh-axis",
    categoryLabel: "Growth-hormone research",
    lotId: "VRL-CJC-2602",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/cjc-1295-5mg.jpg",
    shortDesc:
      "A tetrasubstituted analog of GHRH(1-29) engineered for metabolic stability. Widely used in preclinical research on pulsatile growth hormone release.",
    fromPrice: 39,
    formula: "C₁₅₂H₂₅₂N₄₄O₄₂",
    molecularWeight: "3367.95 g/mol",
    sequence: "Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Met-Ser-Arg-NH₂",
    residues: 29,
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-02",
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    subtitle: "Selective GH secretagogue",
    category: "gh-axis",
    categoryLabel: "Growth-hormone research",
    lotId: "VRL-IPA-2601",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/ipamorelin-5mg.jpg",
    shortDesc:
      "A pentapeptide growth hormone secretagogue receptor agonist developed as a research tool for selective GH release without significant cortisol or prolactin elevation in published preclinical models.",
    fromPrice: 39,
    formula: "C₃₈H₄₉N₉O₅",
    molecularWeight: "711.86 g/mol",
    sequence: "Aib-His-D-2Nal-D-Phe-Lys-NH₂",
    residues: 5,
    cas: "170851-70-4",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-03-15",
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    subtitle: "TH9507",
    category: "gh-axis",
    categoryLabel: "Growth-hormone research",
    lotId: "VRL-TES-2601",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/tesamorelin-5mg.jpg",
    shortDesc:
      "A synthetic analog of human GHRH(1-44) stabilized by N-terminal trans-3-hexenoic acid. A GHRH analog studied in GH/IGF-1 axis and adipose-tissue pathway literature.",
    fromPrice: 79,
    formula: "C₂₂₁H₃₆₆N₇₂O₆₇S",
    molecularWeight: "5135.92 g/mol",
    sequence: "trans-3-hexenoyl-GHRH(1-44)",
    residues: 44,
    cas: "218949-48-5",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-03-29",
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    subtitle: "GLP-1 receptor agonist",
    category: "metabolic",
    categoryLabel: "Metabolic",
    lotId: "VRL-SEM-2604",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/semaglutide-5mg.jpg",
    shortDesc:
      "A long-acting analog of human glucagon-like peptide-1 with extensive published literature across glycemic, weight, and cardiovascular research endpoints.",
    fromPrice: 69,
    formula: "C₁₈₇H₂₉₁N₄₅O₅₉",
    molecularWeight: "4113.58 g/mol",
    sequence: "Fatty-acid-conjugated GLP-1(7-37) analogue",
    residues: 31,
    cas: "910463-68-2",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-10",
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    subtitle: "GIP/GLP-1 dual agonist",
    category: "metabolic",
    categoryLabel: "Metabolic",
    lotId: "VRL-TIR-2603",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/tirzepatide-5mg.jpg",
    shortDesc:
      "A synthetic 39-amino-acid peptide engineered as a unimolecular dual agonist at the GIP and GLP-1 receptors. Extensive recent literature in glycemic and metabolic pathway research.",
    fromPrice: 79,
    formula: "C₂₂₅H₃₄₈F₂N₄₈O₆₈",
    molecularWeight: "4813.45 g/mol",
    sequence: "39-residue dual-agonist analogue",
    residues: 39,
    cas: "2023788-19-2",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-04",
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    subtitle: "LY3437943",
    category: "metabolic",
    categoryLabel: "Metabolic",
    lotId: "VRL-RET-2604",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/retatrutide-5mg.jpg",
    shortDesc:
      "A next-generation synthetic peptide engineered as a unimolecular triple agonist at the GIP, GLP-1, and glucagon receptors. Actively studied in Phase 2/3 trials and an object of intense research interest.",
    fromPrice: 99,
    formula: "C₂₂₁H₃₄₆N₆₀O₆₂",
    molecularWeight: "4731.42 g/mol",
    sequence: "39-residue triple-agonist analogue",
    residues: 39,
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-08",
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    subtitle: "Mitochondrial-derived peptide",
    category: "metabolic",
    categoryLabel: "Metabolic",
    lotId: "VRL-MOT-2603",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/mots-c-5mg.jpg",
    shortDesc:
      "A 16-amino-acid peptide encoded within the mitochondrial 12S rRNA region, studied as a metabolic signaling molecule and modulator of AMPK-dependent pathways.",
    fromPrice: 89,
    formula: "C₁₀₀H₁₅₅N₂₇O₂₂S₃",
    molecularWeight: "2174.59 g/mol",
    sequence: "MRWQEMGYIFYPRKLR",
    residues: 16,
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-03-30",
  },
  {
    slug: "epitalon",
    name: "Epitalon",
    subtitle: "Epithalon · Ala-Glu-Asp-Gly",
    category: "longevity",
    categoryLabel: "Aging biology research",
    lotId: "VRL-EPI-2602",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/epitalon-10mg.jpg",
    shortDesc:
      "A short tetrapeptide first characterized in Russian longevity research as a putative bioregulator of pineal function and telomerase activity in preclinical models.",
    fromPrice: 45,
    formula: "C₁₄H₂₂N₄O₉",
    molecularWeight: "390.35 g/mol",
    sequence: "Ala-Glu-Asp-Gly",
    residues: 4,
    cas: "307297-39-8",
    appearance: "White lyophilized powder",
    storage: "Ambient handling, lyophilized",
    signedOn: "2026-02-26",
  },
  {
    slug: "pt-141",
    name: "PT-141",
    subtitle: "Bremelanotide",
    category: "sexual",
    categoryLabel: "Melanocortin research",
    lotId: "VRL-PT1-2601",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/pt-141-10mg.jpg",
    shortDesc:
      "A cyclic heptapeptide analog of α-MSH acting at central melanocortin receptors. Studied as a melanocortin receptor research tool across central signaling literature.",
    fromPrice: 49,
    formula: "C₅₀H₆₈N₁₄O₁₀",
    molecularWeight: "1025.18 g/mol",
    sequence: "Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH",
    residues: 7,
    cas: "189691-06-3",
    appearance: "White lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-03-08",
  },
  {
    slug: "nad-plus",
    name: "NAD+ 500mg",
    subtitle: "β-Nicotinamide Adenine Dinucleotide",
    category: "metabolic",
    categoryLabel: "Metabolic",
    lotId: "VRL-NAD-2603",
    purityLabel: "≥99% HPLC",
    image: "/images/mockups/nad-plus-500mg.jpg",
    shortDesc:
      "The oxidized form of nicotinamide adenine dinucleotide, supplied as a research-grade reference standard for redox biology, mitochondrial function, and sirtuin-pathway studies.",
    fromPrice: 79,
    formula: "C₂₁H₂₇N₇O₁₄P₂",
    molecularWeight: "663.43 g/mol",
    sequence: "Coenzyme · oxidised form",
    cas: "53-84-9",
    appearance: "White-to-cream lyophilized powder",
    storage: "Store lyophilized at −20 °C, protected from light",
    signedOn: "2026-03-04",
  },
  {
    slug: "bbg70",
    name: "BBG70",
    subtitle: "BPC-157 + GHK-CU + TB-500",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-BBG70-2604",
    purityLabel: "Each component ≥99% HPLC",
    image: "/images/mockups/bbg70-70mg.jpg",
    shortDesc:
      "A 70 mg multi-peptide research stack combining BPC-157 10 mg, GHK-Cu 50 mg, and TB-500 10 mg in one vial. Positioned for pathway-combination studies spanning connective tissue, fibroblast signaling, and tissue remodeling research.",
    fromPrice: 129,
    formula: "Three-peptide co-lyophilized blend",
    molecularWeight: "70 mg per vial total",
    sequence: "BPC-157 · GHK-Cu · TB-500",
    appearance: "White-to-pale-blue lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-14",
  },
  {
    slug: "klow-stack",
    name: "KLOW",
    subtitle: "BPC-157 + GHK-Cu + TB-500 + KPV",
    category: "repair",
    categoryLabel: "Tissue pathway research",
    lotId: "VRL-KLW-2601",
    purityLabel: "Each component ≥99% HPLC",
    image: "/images/mockups/klow-stack-80mg.jpg",
    shortDesc:
      "An 80 mg multi-peptide research stack combining BPC-157 10 mg, GHK-Cu 50 mg, TB-500 10 mg, and KPV 10 mg in one vial, positioned for investigators studying overlapping matrix biology, fibroblast, barrier, and inflammatory signaling pathways.",
    fromPrice: 139,
    formula: "Four-peptide co-lyophilized blend",
    molecularWeight: "80 mg per vial total",
    sequence: "BPC-157 · GHK-Cu · TB-500 · KPV",
    appearance: "White-to-pale-blue lyophilized powder",
    storage: "Store lyophilized at −20 °C",
    signedOn: "2026-04-21",
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function productsInCategory(cat: string): Product[] {
  if (!cat || cat === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === cat);
}
